/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Frame } from "./Frame";
import { FrameCountArgs } from "./FrameCountArgs";
import { FrameFindManyArgs } from "./FrameFindManyArgs";
import { FrameFindUniqueArgs } from "./FrameFindUniqueArgs";
import { CreateFrameArgs } from "./CreateFrameArgs";
import { UpdateFrameArgs } from "./UpdateFrameArgs";
import { DeleteFrameArgs } from "./DeleteFrameArgs";
import { Bot } from "../../bot/base/Bot";
import { FrameService } from "../frame.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Frame)
export class FrameResolverBase {
  constructor(
    protected readonly service: FrameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "read",
    possession: "any",
  })
  async _framesMeta(
    @graphql.Args() args: FrameCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Frame])
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "read",
    possession: "any",
  })
  async frames(@graphql.Args() args: FrameFindManyArgs): Promise<Frame[]> {
    return this.service.frames(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Frame, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "read",
    possession: "own",
  })
  async frame(
    @graphql.Args() args: FrameFindUniqueArgs
  ): Promise<Frame | null> {
    const result = await this.service.frame(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Frame)
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "create",
    possession: "any",
  })
  async createFrame(@graphql.Args() args: CreateFrameArgs): Promise<Frame> {
    return await this.service.createFrame({
      ...args,
      data: {
        ...args.data,

        bot: args.data.bot
          ? {
              connect: args.data.bot,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Frame)
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "update",
    possession: "any",
  })
  async updateFrame(
    @graphql.Args() args: UpdateFrameArgs
  ): Promise<Frame | null> {
    try {
      return await this.service.updateFrame({
        ...args,
        data: {
          ...args.data,

          bot: args.data.bot
            ? {
                connect: args.data.bot,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Frame)
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "delete",
    possession: "any",
  })
  async deleteFrame(
    @graphql.Args() args: DeleteFrameArgs
  ): Promise<Frame | null> {
    try {
      return await this.service.deleteFrame(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Bot, {
    nullable: true,
    name: "bot",
  })
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "read",
    possession: "any",
  })
  async getBot(@graphql.Parent() parent: Frame): Promise<Bot | null> {
    const result = await this.service.getBot(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
