/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FrameService } from "../frame.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FrameCreateInput } from "./FrameCreateInput";
import { Frame } from "./Frame";
import { FrameFindManyArgs } from "./FrameFindManyArgs";
import { FrameWhereUniqueInput } from "./FrameWhereUniqueInput";
import { FrameUpdateInput } from "./FrameUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FrameControllerBase {
  constructor(
    protected readonly service: FrameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Frame })
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFrame(@common.Body() data: FrameCreateInput): Promise<Frame> {
    return await this.service.createFrame({
      data: {
        ...data,

        bot: data.bot
          ? {
              connect: data.bot,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        sequence: true,
        content: true,

        bot: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Frame] })
  @ApiNestedQuery(FrameFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async frames(@common.Req() request: Request): Promise<Frame[]> {
    const args = plainToClass(FrameFindManyArgs, request.query);
    return this.service.frames({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        sequence: true,
        content: true,

        bot: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Frame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async frame(
    @common.Param() params: FrameWhereUniqueInput
  ): Promise<Frame | null> {
    const result = await this.service.frame({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        sequence: true,
        content: true,

        bot: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Frame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFrame(
    @common.Param() params: FrameWhereUniqueInput,
    @common.Body() data: FrameUpdateInput
  ): Promise<Frame | null> {
    try {
      return await this.service.updateFrame({
        where: params,
        data: {
          ...data,

          bot: data.bot
            ? {
                connect: data.bot,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          sequence: true,
          content: true,

          bot: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Frame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Frame",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFrame(
    @common.Param() params: FrameWhereUniqueInput
  ): Promise<Frame | null> {
    try {
      return await this.service.deleteFrame({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          sequence: true,
          content: true,

          bot: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
